### PR TITLE
Complete the sample

### LINKED ISSUE #1: It’s not clear what you’re trying to test
the test defined at 

https://github.com/mehdihadeli/test/blob/c8f7a271b9092c39e794884f64102cd0bcc5453d/SampleMiddlewareTests.cs#L6

tests nothing. What are you trying to test?

### PR DESCRIPTION
**Pull request by mauroservienti**
Fix #1

### CODE REVIEW

**Comment by mehdihadeli** [comment]
@mauroservienti So thanks for completing my example, let me check it out :)

**Comment by mehdihadeli** [comment]
@mauroservienti It works perfectly, Thank you ;)

**Comment by mauroservienti** [comment]
Cool. Can I mention you and refer to this repository on the original blog post?

**Comment by mehdihadeli** [comment]
@mauroservienti  Sure :) 
But I have a problem now, when I added a custom [ConfigureWebHost](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L27) to `WebApplicationFactoryWithHost`.
With doing this, our [Configure Delegate](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/SampleMiddlewareTests.cs#L42) in test doesn't call and just our [Configure Delegate](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L32) in `ConfigureWebHost` will call.
I test the same approach with a real web app with program.cs, and it worked. I think the problem is with creating [HostBuilder](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L49) manually. What do you think?

**Comment by mauroservienti** [comment]
Push the changes to a pull request, I'll have a look.

**Comment by mauroservienti** [comment]
Why do you want to use a WebHost? WebHost exists purely for backward compatibility in ASP.Net

**Comment by mehdihadeli** [comment]
It's on main branch now,
In Microsoft docs for customization of factory uses [ConfigureWebHost](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#customize-webapplicationfactory) and I want to have capability of overriding or adding some settings to `ConfigureServices` and `Configure` and `WebHost` have both of these. For example, I added [logging to Xunit Output](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L39) for all tests

**Comment by mauroservienti** [comment]
That's not how it works if you wanna use the web host factory in tests. You can already configure both services and the application without the need for the web host.

In fact, the sample tests in the Test project are customizing the application by using custom delegates.

**Comment by mehdihadeli** [comment]
You're right, but my purpose was for example configuring some share things between all tests and prevent DRY like [logging to Xunit Output](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L39). It can move to `CreateHost` method also.

**Pull request merged**
